<a href="https://colab.research.google.com/github/Thilak-K21/ML-LAB/blob/main/1WA23CS021_ML_LAB10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('heart.csv')

print("Original DataFrame head:")
display(df.head())
print("\nOriginal DataFrame info:")
df.info()

Original DataFrame head:

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

Original DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

First, let's identify the categorical columns that are of `object` dtype.

In [3]:
categorical_cols = df.select_dtypes(include='object').columns

print("Categorical columns in the dataset are:", categorical_cols.tolist())

Categorical columns in the dataset are: ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

Now, we'll apply Label Encoding to specific binary or ordinal categorical columns and One-Hot Encoding to nominal categorical columns. For this dataset, we'll use Label Encoding for `Sex` and `ExerciseAngina` and One-Hot Encoding for `ChestPainType`, `RestingECG`, `ST_Slope`.

In [7]:
label_encoder = LabelEncoder()

le_cols = ['Sex', 'ExerciseAngina']

for col in le_cols:
    if col in df.columns:
        df[col] = label_encoder.fit_transform(df[col])
        print(f"Label encoded '{col}': {label_encoder.classes_} is converted to  {label_encoder.transform(label_encoder.classes_)}")

ohe_cols = ['ChestPainType', 'RestingECG', 'ST_Slope']

existing_ohe_cols = [col for col in ohe_cols if col in df.columns]

if existing_ohe_cols:
    df = pd.get_dummies(df, columns=existing_ohe_cols, drop_first=True, dtype=int)
    print(f"One-Hot Encoded columns: {existing_ohe_cols}")
else:
    print("One-Hot Encoding columns (ChestPainType, RestingECG, ST_Slope) already processed or not found.")


print("\nDataFrame after encoding head:")
display(df.head())
print("\nDataFrame after encoding info:")
df.info()

Label encoded 'Sex': [0 1] -> [0 1]
Label encoded 'ExerciseAngina': [0 1] -> [0 1]
One-Hot Encoding columns (ChestPainType, RestingECG, ST_Slope) already processed or not found.

DataFrame after encoding head:

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0,0.0,0,1,0,0,1,0,0,1
1,49,0,160,180,0,156,0,1.0,1,0,1,0,1,0,1,0
2,37,1,130,283,0,98,0,0.0,0,1,0,0,0,1,0,1
3,48,0,138,214,0,108,1,1.5,1,0,0,0,1,0,1,0
4,54,1,150,195,0,122,0,0.0,0,0,1,0,1,0,0,1

DataFrame after encoding info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                918 non-null    int64
 1   Sex                918 non-null    int64
 2   RestingBP          918 non-null    int64
 3   Cholesterol        918 non-null    int64
 4   FastingBS          918 non-null    int64
 5   MaxHR              918 non-null    int64
 6   ExerciseAngina     918 non-null    int64
 7   Oldpeak            918 non-null    float64
 8   HeartDisease       918 non-null    int64
 9   ChestPainType_ATA  918 non-null    int64
 10  ChestPainType_NAP  918 non-null    int64
 11  ChestPainType_TA   918 non-null    int64
 12  RestingECG_Normal  918 non-null    int64
 13  RestingECG_ST      918 non-null    int64
 14  ST_Slope_Flat      918 non-null    int64
 15  ST_Slope_Up        918 non-null    int64
dtypes: float64(1), int64(15)
memory usage: 114.9 KB

**Apply scaling**

In [8]:
from sklearn.preprocessing import StandardScaler

numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

if 'HeartDisease' in numerical_cols: #this is thr trget variable so we dont removve it
    numerical_cols.remove('HeartDisease')

print(f"Numerical columns to be scaled: {numerical_cols}")

scaler = StandardScaler()

df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

print("\nDataFrame after scaling head:")
display(df.head())
print("\nDataFrame after scaling info:")
df.info()

Numerical columns to be scaled: ['Age', 'Sex', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ChestPainType_ATA', 'ChestPainType_NAP', 'ChestPainType_TA', 'RestingECG_Normal', 'RestingECG_ST', 'ST_Slope_Flat', 'ST_Slope_Up']

DataFrame after scaling head:

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,ExerciseAngina,Oldpeak,HeartDisease,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ST_Slope_Flat,ST_Slope_Up
0,-1.433140,0.515952,0.410909,0.825070,-0.551341,1.382928,-0.823556,-0.832432,0,2.075177,-0.532838,-0.229679,0.814275,-0.490449,-1.002181,1.150674
1,-0.478484,-1.938163,1.491752,-0.171961,-0.551341,0.754157,-0.823556,0.105664,1,-0.481887,1.876744,-0.229679,0.814275,-0.490449,0.997824,-0.869056
2,-1.751359,0.515952,-0.129513,0.770188,-0.551341,-1.525138,-0.823556,-0.832432,0,2.075177,-0.532838,-0.229679,-1.228087,2.038947,-1.002181,1.150674
3,-0.584556,-1.938163,0.302825,0.139040,-0.551341,-1.132156,1.214246,0.574711,1,-0.481887,-0.532838,-0.229679,0.814275,-0.490449,0.997824,-0.869056
4,0.051881,0.515952,0.951331,-0.034755,-0.551341,-0.581981,-0.823556,-0.832432,0,-0.481887,1.876744,-0.229679,0.814275,-0.490449,-1.002181,1.150674

DataFrame after scaling info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                918 non-null    float64
 1   Sex                918 non-null    float64
 2   RestingBP          918 non-null    float64
 3   Cholesterol        918 non-null    float64
 4   FastingBS          918 non-null    float64
 5   MaxHR              918 non-null    float64
 6   ExerciseAngina     918 non-null    float64
 7   Oldpeak            918 non-null    float64
 8   HeartDisease       918 non-null    int64
 9   ChestPainType_ATA  918 non-null    float64
 10  ChestPainType_NAP  918 non-null    float64
 11  ChestPainType_TA   918 non-null    float64
 12  RestingECG_Normal  918 non-null    float64
 13  RestingECG_ST      918 non-null    float64
 14  ST_Slope_Flat      918 non-null    float64
 15  ST_Slope_Up        918 non-null    float64
dtypes: float64(15), int64(1)
memory usage: 114.9 KB

###Build a classification model using various methods (SVM, logistic regression, random forest) and check which model gives you the best accuracy **bold text**

In [9]:
X = df.drop('HeartDisease', axis=1)
y = df['HeartDisease']

print("Features (X) shape:", X.shape)
print("Target (y) shape:", y.shape)

Features (X) shape: (918, 15)
Target (y) shape: (918,)

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (734, 15)
X_test shape: (184, 15)
y_train shape: (734,)
y_test shape: (184,)

### Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

log_reg_model = LogisticRegression(random_state=42, solver='liblinear') # 'liblinear' is good for small datasets and handles L1/L2 penalties
log_reg_model.fit(X_train, y_train)

y_pred_lr = log_reg_model.predict(X_test)

accuracy_lr = accuracy_score(y_test, y_pred_lr)
print(f"Logistic Regression Accuracy: {accuracy_lr:.4f}")

Logistic Regression Accuracy: 0.8859

### Support Vector Machine (SVM)

In [12]:
from sklearn.svm import SVC

svm_model = SVC(random_state=42)
svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"SVM Accuracy: {accuracy_svm:.4f}")

SVM Accuracy: 0.9022

### Random Forest Classifier

In [13]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Accuracy: {accuracy_rf:.4f}")

Random Forest Accuracy: 0.8750

### Best model out of the all

In [14]:
model_accuracies = {
    'Logistic Regression': accuracy_lr,
    'SVM': accuracy_svm,
    'Random Forest': accuracy_rf
}

best_model_name = max(model_accuracies, key=model_accuracies.get)
best_accuracy = model_accuracies[best_model_name]

print("\n--- Model Accuracies ---")
for model, accuracy in model_accuracies.items():
    print(f"{model}: {accuracy:.4f}")

print(f"\nThe best performing model is {best_model_name} with an accuracy of {best_accuracy:.4f}.")

--- Model Accuracies ---
Logistic Regression: 0.8859
SVM: 0.9022
Random Forest: 0.8750

The best performing model is SVM with an accuracy of 0.9022.

###Now use PCA to reduce dimensions, retrain your model and see what impact it has on your model in terms of accuracy. Keep in mind that many times doing PCA reduces the accuracy but computation is much lighter and that's the trade off you need to consider while building models in real life.

### Apply PCA for Dimensionality Reduction

In [16]:
from sklearn.decomposition import PCA

pca = PCA(n_components=0.95, random_state=42)

X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

print(f"Original number of features: {X_train.shape[1]}")
print(f"Number of features after PCA: {X_train_pca.shape[1]}")
print(f"Explained variance ratio: {pca.explained_variance_ratio_.sum():.4f}")

Original number of features: 15
Number of features after PCA: 13
Explained variance ratio: 0.9722

### Retrain Models with PCA-transformed Data

#### Logistic Regression with PCA

In [17]:
log_reg_model_pca = LogisticRegression(random_state=42, solver='liblinear')
log_reg_model_pca.fit(X_train_pca, y_train)

y_pred_lr_pca = log_reg_model_pca.predict(X_test_pca)

accuracy_lr_pca = accuracy_score(y_test, y_pred_lr_pca)
print(f"Logistic Regression Accuracy (with PCA): {accuracy_lr_pca:.4f}")

Logistic Regression Accuracy (with PCA): 0.8913

#### Support Vector Machine (SVM) with PCA

In [18]:
svm_model_pca = SVC(random_state=42)
svm_model_pca.fit(X_train_pca, y_train)

y_pred_svm_pca = svm_model_pca.predict(X_test_pca)

accuracy_svm_pca = accuracy_score(y_test, y_pred_svm_pca)
print(f"SVM Accuracy (with PCA): {accuracy_svm_pca:.4f}")

SVM Accuracy (with PCA): 0.9022

#### Random Forest Classifier with PCA

In [19]:
rf_model_pca = RandomForestClassifier(random_state=42)
rf_model_pca.fit(X_train_pca, y_train)

y_pred_rf_pca = rf_model_pca.predict(X_test_pca)

accuracy_rf_pca = accuracy_score(y_test, y_pred_rf_pca)
print(f"Random Forest Accuracy (with PCA): {accuracy_rf_pca:.4f}")

Random Forest Accuracy (with PCA): 0.8859

### Comparison of Model Accuracies (with and without PCA)

In [20]:
model_accuracies_pca = {
    'Logistic Regression (Original)': accuracy_lr,
    'SVM (Original)': accuracy_svm,
    'Random Forest (Original)': accuracy_rf,
    'Logistic Regression (PCA)': accuracy_lr_pca,
    'SVM (PCA)': accuracy_svm_pca,
    'Random Forest (PCA)': accuracy_rf_pca
}

print("\n--- Model Accuracies Comparison ---")
for model, accuracy in model_accuracies_pca.items():
    print(f"{model}: {accuracy:.4f}")

--- Model Accuracies Comparison ---
Logistic Regression (Original): 0.8859
SVM (Original): 0.9022
Random Forest (Original): 0.8750
Logistic Regression (PCA): 0.8913
SVM (PCA): 0.9022
Random Forest (PCA): 0.8859